version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: express-app
    restart: always
    depends_on:
      - mysql
    env_file: ./.env
    environment:
      PORT: ${NODE_LOCAL_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${MYSQLDB_DATABASE}
      DB_USER: ${MYSQLDB_USER}
      DB_PASS: ${MYSQLDB_ROOT_PASSWORD}
      DB_HOST: "mysql"
      DB_PORT: ${MYSQLDB_DOCKER_PORT}
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "nodemon", "dist/index.js"]

volumes:
  mysql_data:
